### ISSUE TITLE
new problem 1.04

### ISSUE THREAD

**Issue by border999** [phantamanta44/tinkers-evolution#1]
[crash-2020-05-28_08.16.26-client.txt](https://github.com/phantamanta44/tinkers-evolution/files/4697478/crash-2020-05-28_08.16.26-client.txt)

**Comment by phantamanta44** [comment]
i would like to see a debug log if possible

**Comment by border999** [comment]
[debug.log](https://github.com/phantamanta44/tinkers-evolution/files/4698070/debug.log)
[latest.log](https://github.com/phantamanta44/tinkers-evolution/files/4698071/latest.log)

**Comment by phantamanta44** [comment]
thanks. i've found the problem and will fix soon

**Comment by phantamanta44** [comment]
this release should do the trick: https://www.curseforge.com/minecraft/mc-mods/tinkers-evolution/files/2967774

**Comment by border999** [comment]
[crash-2020-05-28_13.01.13-client.txt](https://github.com/phantamanta44/tinkers-evolution/files/4698721/crash-2020-05-28_13.01.13-client.txt)
[latest.log](https://github.com/phantamanta44/tinkers-evolution/files/4698724/latest.log)
[debug.log](https://github.com/phantamanta44/tinkers-evolution/files/4698725/debug.log)

**Comment by border999** [comment]
new 1.0.4

**Comment by phantamanta44** [comment]
what the heck

**Comment by phantamanta44** [comment]
second try's the charm: https://www.curseforge.com/minecraft/mc-mods/tinkers-evolution/files/2967804

**Comment by border999** [comment]
this time it worked
