### ISSUE TITLE
Ideas: Superconductive Redstone plus Forestry integration

### ISSUE THREAD

**Issue by MusicMaestro123** [phantamanta44/tinkers-evolution#10]
I have an idea that perhaps if you alloy redstone, gold and iron together it would make superconductive redstone which could be turned into blocks and form superconductive redstone dust which could have a maximum signal stength of 30. It would also be able to upgrade tools with the maximum amount haste to be 10x faster.

On the subject of Forestry integration perhaps woven silk having the modifier apiarist's protection which protects you against the attacks of bees and also apatite added as a material which when used on scythes, kamas and mattocks makes them able to till ground that the becomes instantly irrigated.

And keep up the good work :)

**Comment by phantamanta44** [comment]
for the first idea, i think "superconductive redstone wire" is outside the scope of the mod. moreover, i don't really want to buff the haste modifier and especially not 10x

as for forestry integration, i completely forgot that mod existed. i'll add it to the to-do list

**Comment by MusicMaestro123** [comment]
Perhaps an enchantable modifier that adds whatever enchantment it has enchanted on it to the tool?

**Comment by phantamanta44** [comment]
i don't think so. the entire point of tinkers' modifiers is to replace enchantments

**Comment by MusicMaestro123** [comment]
However if you put the scarab beetle(modifier is called Scarab Beetle in red) on to the new sceptre it doesn't show up properly. The Scarab beetle is from fossils and archaeology revived which increases mining speed, mining level, attack damage and attack cooldown I think.

**Comment by SonicX8000** [comment]
> 
> 
> However if you put the scarab beetle(modifier is called Scarab Beetle in red) on to the new sceptre it doesn't show up properly. The Scarab beetle is from fossils and archaeology revived which increases mining speed, mining level, attack damage and attack cooldown I think.

That occurs with any non-vanilla tinkers tool, since there's no texture for them for the Scarab Beetle Modifier. I dunno if Fossils would have to add in the texture since the modifier comes directly from Fossils.

**Comment by MusicMaestro123** [comment]
Very well then!
