### ISSUE TITLE
JAOPCA compatibility issues.

### ISSUE THREAD

**Issue by paypur** [phantamanta44/tinkers-evolution#101]
Smelting starmetal produces the JAOPCA molten starmetal which makes impossible to make tools with. tconevo-1.12.2-1.0.33 and JAOPCA-1.12.2-2.2.8.103

**Comment by Handeril** [comment]
Try searching "astral_starmetal" in JAOPCA.cfg [under config folder] and adding "molten" to the blacklisted modules.

Example:

    # The module blacklist for this material. * will mean all modules.
    S:moduleBlacklist <
	   molten
     >

**Comment by paypur** [comment]
Fixed. I have a feeling the affects some other metals too.
