### ISSUE TITLE
Crash on start with SolarFlux Reborn

### ISSUE THREAD

**Issue by randomuser818** [phantamanta44/tinkers-evolution#102]
Hi, 

I believe I've encountered similar error to the one with Ender:IO, but with SolarFlux Reborn instead. There is crash report in the attachment. 

Thanks,
M.

[crash-2021-06-11_14.54.46-client.txt](https://github.com/phantamanta44/tinkers-evolution/files/6638663/crash-2021-06-11_14.54.46-client.txt)

**Comment by phantamanta44** [comment]
i think your solar flux version might be outdated
