### ISSUE TITLE
there's a bug when using botania materials

### ISSUE THREAD

**Issue by linxcy** [phantamanta44/tinkers-evolution#11]
if the tool has gaia's wrath traits ,the game will crash after slash the air.

[latest.log](https://github.com/phantamanta44/tinkers-evolution/files/4858704/latest.log)
[debug.log](https://github.com/phantamanta44/tinkers-evolution/files/4858705/debug.log)

**Comment by phantamanta44** [comment]
i suspect this might be an issue on forge .2854; could you see if the bug still happens on .2847?

**Comment by linxcy** [comment]
The game still crash with forge 2847.
And also the same problem.
[debug.log](https://github.com/phantamanta44/tinkers-evolution/files/4861382/debug.log)
[latest.log](https://github.com/phantamanta44/tinkers-evolution/files/4861383/latest.log)

**Comment by linxcy** [comment]
> i suspect this might be an issue on forge .2854; could you see if the bug still happens on .2847?

The game still crash with forge 2847.

**Comment by phantamanta44** [comment]
could you possibly try running with a hotspot vm instead of openj9?

**Comment by linxcy** [comment]
> could you possibly try running with a hotspot vm instead of openj9?

still crash.
[debug.log](https://github.com/phantamanta44/tinkers-evolution/files/4862475/debug.log)
[latest.log](https://github.com/phantamanta44/tinkers-evolution/files/4862479/latest.log)

**Comment by phantamanta44** [comment]
what the heck

**Comment by phantamanta44** [comment]
i think i finally pinned this one down. what an annoying issue...
