### ISSUE TITLE
Fluxed modifier not applying.

### ISSUE THREAD

**Issue by The-Scout** [phantamanta44/tinkers-evolution#112]
https://i.imgur.com/5LPdHEf.png reinforced flux capacitor is not working, hardened specifically works

**Comment by phantamanta44** [comment]
by default, your armour needs at least 1/2000 of the battery's capacity in durability for fluxed to apply. you can check the config to see what the exact value is in the modpack you're playing

**Comment by The-Scout** [comment]
Right thanks!, that makes much more sense now.
