### ISSUE TITLE
[Feature Request] Thaumcraft Infusion Enchantments

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/tinkers-evolution#12]
<sub><sup>Im very excited of your work! You not just tweaking parameters of tools, but add unique mod-related stuff to make materials act as in their normal form. Big fan!</sup></sub>

Thaumcraft 6 have thing called [Infusion Enchantment](https://minecraftguides.net/tc6/arcane-infusion/infusion-enchantment). 
Most interesteing in them is `Burrowing` (The furthest block will be harvested, not your target block) and `Refining` (Chance of Native clusters dropping from Ores).
<img src="https://i.imgur.com/R9MThaF.png" width=80>
<img src="https://i.imgur.com/fsGbJiC.png" width=70>

It would be great, if TCon tools can have this enchantments. But same as Tinker's instruments have their enchants in form of **modifiers**, it would be great if Borrowing and Refining 1-4 would be in form of modifiers too.

Borrowing should multiply number of dropped clusters with Luck modifier, same as with Smelting.
<img src="https://i.imgur.com/Cy1Ocnd.png" width=100>
Would be great if [Astral Sorcery amulet](https://minecraftguides.net/AS/constellation/resplendent%20prism) increased level of this enchants too.
<img src="https://i.imgur.com/DdqDAmO.png" width=35>

**Comment by MusicMaestro123** [comment]
Sounds cool!

**Comment by phantamanta44** [comment]
admittedly i've never gotten very far into tc6, so my thaum integration is pretty surface-level. i'll look into it

**Comment by MusicMaestro123** [comment]
Would be cool if it added the others as modifiers as well because they sound pretty good!

**Comment by Krutoy242** [comment]
Thank you! Gonna test it when released
