### ISSUE TITLE
Tinkers'Evolution crash bug with RedstoneRepositoryRevolved

### ISSUE THREAD

**Issue by EringMantis831** [phantamanta44/tinkers-evolution#120]
Game will crash when installed TConEvo and RedstoneRepositoryRevolved[Latest Version] in a same game.
I think there's a compatible bug in ur mod. The bug made your mode can't compatible RRR-1.12.2-2.0.0[realese]
Fix it, plz

**Comment by phantamanta44** [comment]
duplicate of #114
