### ISSUE TITLE
The modifier 'Astral' of the TconEvo has some problems

### ISSUE THREAD

**Issue by EdwinYoungSteve** [phantamanta44/tinkers-evolution#127]
If you custom the TIC material (using pewter or contenttweaker) with the Astral Modifier, The tool's NBT which has this modifier will be cleared when attuned on the attunement altar.

Thanks.

**Comment by EdwinYoungSteve** [comment]
![image](https://github.com/phantamanta44/tinkers-evolution/assets/99588600/eaa53e34-bc49-4713-949e-566dc28d4a62)
![image](https://github.com/phantamanta44/tinkers-evolution/assets/99588600/af6dc04f-3b91-44a8-ad07-903cee1e45c2)
![image](https://github.com/phantamanta44/tinkers-evolution/assets/99588600/73dbd404-125e-43ee-96d4-94e8e18c3f31)
![image](https://github.com/phantamanta44/tinkers-evolution/assets/99588600/51f2be5d-db26-4654-bc7e-2f39008fe9d8)

**Comment by EdwinYoungSteve** [comment]
@LXGaming
here are the details

**Comment by Krutoy242** [comment]
Can confirm, happens to `E2E-E` player too:

![image](https://github.com/phantamanta44/tinkers-evolution/assets/936618/29006881-323a-4bd2-86a1-54b375720e1a)

**Comment by phantamanta44** [comment]
ok, i've figured out that in e2e:e, it's a conflict with random tweaker, which does essentially the same coremod hack as tconevo to mess with the attunement altar. not sure if that's also the same problem as the OP

**Comment by Krutoy242** [comment]
Should i report it to `random tweaker` mod issues?

**Comment by phantamanta44** [comment]
i plan on changing the way my patch works so that it's less intrusive, and so the random patches guys shouldn't need to do anything on their end. it might still be useful to let them know that this conflict can happen, i guess?

**Comment by phantamanta44** [comment]
really the problem is that the astral sorcery attunement altar code is not designed for this sort of thing at all, but of course AS 1.12 is no longer supported, so there's no chance of any fix happening there

**Comment by Krutoy242** [comment]
Voiding NBT data on AS infusion wasn't fixed. Players still report this issue even on version `tconevo-1.12.2-1.0.48`

https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/318

How can i avoid voiding TCon tools?

**Comment by phantamanta44** [comment]
that's a bit embarrassing, but I'll chalk it up to being rusty after taking such a long break
