### ISSUE TITLE
[1.12.2] Aftershock Trait of different levels have their own bonus damage hit splats.

### ISSUE THREAD

**Issue by SonicX8000** [phantamanta44/tinkers-evolution#128]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods:
Avaritia-1.12.2-3.3.0.37-universal
BrandonsCore-1.12.2-2.4.20.162-universal 
CodeChickenLib-1.12.2-3.2.3.358-universal 
CoFHCore-1.12.2-4.6.6.1-universal
CoFHWorld-1.12.2-1.4.0.1-universal 
HadEnoughItems_1.12.2-4.24.1 
libnine-1.12.2-1.2.0 
Mantle-1.12-1.3.3.55 
RedstoneArsenal-1.12.2-2.6.4.1-universal 
RedstoneFlux-1.12-2.1.1.1-universal 
RedstoneRepository-1.12.2-1.4.0-dev-universal 
tconevo-1.12.2-1.0.44 
TConstruct-1.12.2-2.13.0.183 
ThermalExpansion-1.12.2-5.5.6.1-universal 
ThermalFoundation-1.12.2-2.6.6.1-universal

---

Aftershock is a Tool Trait that deals bonus magic damage when off cooldown. This can be stacked to III but I noticed that if you apply the traits that have different levels... they will have their own hit splats. Here's a video showing the bug using a Broadsword with Aftershock III and then a Broadsword with Aftershock I, II and III.

https://user-images.githubusercontent.com/36653806/219941731-cff0d8cd-ce99-4db1-a2eb-b311a956dcb0.mp4

Here's a rundown of the Aftershock traits from different materials, these first two appear to work correctly.

Aftershock III (Crystal Matrix)
Damage dealt is "14 + 6" for a total of 20 damage.

Aftershock x 2 = Aftershock II (Singalum, Flux Crystal)
Damage dealt is "10 + 4" for a total of 14 damage.

=====

Now onto the bugged part section using traits that give different levels.

Aftershock + Aftershock II + Aftershock III = Aftershock III (Signalum, Gelid Gem, and Crystal Matrix)
Damage dealt is "14 + 6 + 6 + 6" for a total of 32 damage.

Aftershock + Aftershock II = Aftershock III (Signalum, Gelid Gem)
Damage dealt is "14 + 6 + 6" for a total of 26 damage.

Aftershock II x 3 = Aftershock III (Gelid Gem)
Damage dealt is "14 + 6" for a total of 20 damage.

---

By the looks of it, it seems that if you have different levels of the Aftershock Trait on the tool, you can have it hit many more times than intended.

**Comment by phantamanta44** [comment]
side note: this appears to be a problem with vanilla tcon too: e.g. if you have a tool with both crude 1 and crude 2, you get the damage bonus applied twice on attacks against unarmoured targets
