### ISSUE TITLE
missing texture and stops leveling

### ISSUE THREAD

**Issue by BeardBear33** [phantamanta44/tinkers-evolution#135]
Mod versions
forge 1.12.2 14.23.5.2860
tconevo-1.12.2-1.0.46 (these bugs are not only a problem of this version but also of previous versions)
TConstruct-1.12.2-2.13.0.183
TinkerToolLeveling-1.12.2-1.1.0
conarm-1.12.2-1.2.5.10

TC evolution is a matchmaking mode I just have a minor problem with two bugs and one feature.
1. When I want to look at the recipe for the upgrade key, the armor/tool that is upgraded with the Evolved trait does not have a texture in JEI.
See here https://ibb.co/yY79YXg

2. There is a problem with using the mod to level armor and tools more specifically the moment you upgrade armor (tools work fine) it doesn't get experience until the battery is completely drained

3. Missing possibility to set in config file fly speed for Draconic Evolution module

I apologize for the translation errors. If necessary, at least some info if it can be fixed at all and thus wait or should I look for some alternative solution

**Comment by phantamanta44** [comment]
patched in 8bf1c62c82c4e9183075513bd1d8a173243a03e7, 6edd6db4ac7b86ab373751f45c9bff033db67225, and 85e2a6e41772db9a3b94216f73f9a9cfa8c3124b
