### ISSUE TITLE
[Critical bug] Fix Draconic Evolution JEI

### ISSUE THREAD

**Issue by BeardBear33** [phantamanta44/tinkers-evolution#136]
After this fix, no recipes are displayed via Infusion at all. Here is the error log:

https://pastebin.com/aVNPXt4J

**Comment by phantamanta44** [comment]
can i see a full log, please?

**Comment by BeardBear33** [comment]
Sure here it is. Only basic and required mods to avoid conflicts and newly generated configs
https://pastebin.com/MVt2Lkxv
