### ISSUE TITLE
Hide original draconic evolution upgrade recipe in NEI

### ISSUE THREAD

**Issue by BeardBear33** [phantamanta44/tinkers-evolution#137]
Any chance of adding an option to hide recipes for upgrading original Draconic Evolution tools and armor? Because it still shows them even if they are completely disabled in the DraconicEvolution.cfg itself.
Image for clarification:
https://ibb.co/hKJnQmZ

The thing is that my modpack uses tinkers construct,tinkers construct armory and tinkers evolution as the only possible tools and armor. Unfortunately even though I tried different options to remove it via crafttweaker,moretweaker,draconic custom recipes none of that worked for it.

Unless this can somehow be blocked via tcevolution so nothing happens it's just a small flaw that it in nei now shows still disabled original Draconic stuff for upgrade, the main thing is that you can see the upgrade for conarm and tcon works so awesome.

**Comment by phantamanta44** [comment]
sorry, but this is out of scope. i imagine brandon is probably not willing to patch the 1.12 version of DE any more, so i might suggest asking the [sledgehammer](https://github.com/LXGaming/Sledgehammer/) guys to write a patch for it
