### ISSUE TITLE
`tconevo.integration.avaritia.client.AvaritiaToolModel.bake()` takes too long, about 5 seconds

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/tinkers-evolution#140]
Considering my Spark game load profile, `AvaritiaToolModel.bake()` function alone took about 5 seconds.
If its true, Its too much for one material.

![image](https://github.com/phantamanta44/tinkers-evolution/assets/936618/ba4eb3ef-88cb-4331-a8d6-f7f41e744fbe)

### https://spark.lucko.me/wycUXOGdml

[debug-4.log.gz](https://github.com/phantamanta44/tinkers-evolution/files/14163954/debug-4.log.gz)

I don't know backend of MC or TConEvo, so i understand that it could be false alarm.

But if its actually TConEvo problem, I would like if one material doesn't add 5 seconds to my game load (its about 1%).

If nothing could be improved in building code, I would like to be able to disable fancy custom textures OR disable whole Avaritia module.

**Comment by phantamanta44** [comment]
tconevo replaces *ALL* tool models with its custom wrappers; that's not just the baking time for the infinity material, but for *all* tool materials. it shouldn't significantly impact performance, but you can disable this behaviour by setting `useFancyModelRenders` to false in the config
