### ISSUE TITLE
Sorry still can't smelt or craft Osgloglas 

### ISSUE THREAD

**Issue by jimmy06200** [phantamanta44/tinkers-evolution#15]
Sorry its me again .... i  try this time a lot of thing but still lock with this material/ ingot/ craft.
with your mod i can't craft osgloglas by the tinkers smelter or anything else 
Can you help me with this one ?

**Comment by phantamanta44** [comment]
it seems like plustic uses different fluid IDs for refined glowstone/obsidian. your best bet is probably to disable tconevo's refined glowstone/obsidian so plustic's own fluids are used

**Comment by phantamanta44** [comment]
alternatively, you might be able to use crafttweaker to add a smeltery alloy recipe for it. however, i don't intend to explicitly support plustic in this mod

**Comment by jimmy06200** [comment]
i already disable refined glowstone/obsidian but nothing and i can understand. i am to dumb to use crafttweaker ... thats why i try to find solution. because i cant make one ...

**Comment by phantamanta44** [comment]
hmm... i think there might be a problem with the way i register fluids. looking into it

**Comment by jimmy06200** [comment]
thx =p
