### ISSUE TITLE
Config mods on/off

### ISSUE THREAD

**Issue by jimmy06200** [phantamanta44/tinkers-evolution#17]
Hi its me again 
A little suggestion maybe ?
Can you add a fonction to disable mod ?

I didnt notice until few player mention it, anybody can use refined glowstone/obsidian still in any cast to make tool or weapon.

Config got the disable trait on every Mekanism materails as such 
"
general {
    # A list of tool materials that should be disabled.
    S:disabledMaterials <
        osmium
        refined glowstone
        refined obsidian
     >
"

But still cant do anything and the progression is lock ...
On creative fluids are not register as your mods anymore but cant smelt or alloy them in smeltry ...

Please help again and sorry for all the worries i give you ..

**Comment by phantamanta44** [comment]
you need underscores for `refined_glowstone` and `refined_obsidian`

**Comment by jimmy06200** [comment]
Yes i was dumb its working =p

**Comment by phantamanta44** [comment]
this fix should be obsolete as of 1.0.27, since tconevo fluids can now be used to make plustic allows
