### ISSUE TITLE
Compatibility enigma 2 expert ( plus Tic) and Tconevo

### ISSUE THREAD

**Issue by jimmy06200** [phantamanta44/tinkers-evolution#2]
HI there, huge fan great work here, but huge idiot trying to make the best out of the existing tinkers materials and modifiers and yours works.

I try to blacklist everything and false the overried materials from Mekanism but it messed up the osgloglas material who doenst show up and mess up with other mods like better questing ....

Can you help me with that please ?

**Comment by phantamanta44** [comment]
i'm not really sure what exactly the issue here is... could you clarify a bit?

**Comment by votex09** [comment]
What he is saying is Tinkers Evolution has references to Osgloglas and Osmiridium that conflict with the fork of PlusTic (and apparently invar)

This makes those materials vanish from existence.

![image](https://user-images.githubusercontent.com/10671494/84723053-582ce780-af4a-11ea-856a-57b0ed9f8501.png)

**Comment by jimmy06200** [comment]
Thx to votex09, it is exactly that !! i didnt check everything because i am a noob but thx for the addition =3

**Comment by votex09** [comment]
In response to the recent update:

![image](https://user-images.githubusercontent.com/10671494/84911743-2fa60a00-b07e-11ea-8514-f77c821b2a0b.png)

It's doing this with different materials now.  (tconevo-1.12.2-1.0.14) [libnine-1.12.2-1.1.8]
