### ISSUE TITLE
Idea: Electroblob's Wizardry Compatibility

### ISSUE THREAD

**Issue by MusicMaestro123** [phantamanta44/tinkers-evolution#21]
Just wondering if you could make the sceptres work like the wands from electroblob's so they can use it's spells. Would be cool!

**Comment by phantamanta44** [comment]
too powerful

**Comment by MusicMaestro123** [comment]
Why would it be too powerful you can make the sceptres contain mana and they use it up and have different levels of arcane focuses or a completely new tool dedicated to being a wand that can be levelled up by combining it with different crystals so that  it isn't too op.

**Comment by phantamanta44** [comment]
one design philosophy i'm using here is that each tcon tool should only have a small and very specific set of abilities. there should be trade-offs to selecting one type of weapon over another (i.e. the opportunity cost of the other weapon's ability), and giving any one weapon the flexibility of being able to cast wizardry spells is a clear violation of this principle
