### ISSUE TITLE
Liquids cant be picked from JEI in cheat mode

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/tinkers-evolution#22]
Clicking on liquids in cheat mode usually grant Forge bucket with this liquid, but most fluids from Tinkers Evolution cant be picked this way.
Some liquids (like manasteel or refined obsidian) still can be, but this probably because i have PlusTic insalled.
<img src="https://i.imgur.com/vWGuUbE.png" width=400>

**Comment by phantamanta44** [comment]
oh that's probably because i haven't added bucket items for my liquids. i guess i can do that if you really need them

**Comment by Krutoy242** [comment]
Not in need! I though you intend to at least know this issue exist.
