### ISSUE TITLE
Tconevo = crafttweaker recepies problems

### ISSUE THREAD

**Issue by jimmy06200** [phantamanta44/tinkers-evolution#26]
Hi its me again =p 
When your mods is install with crafttweaker version 4.1.20.581, it makes unable to craft crafttweaker modified recepies and load bot jei recepies ( broken and vanilla/ mod vanilla one ).

Can you please chek if you can do something about it ?

**Comment by ChromaPIE** [comment]
I'm using your version of CrT too. However everything works just fine on my end. Maybe you can try load the game with/without TConEvo and don't change nothing else and see if it truly is this mod that caused your scripts not being loaded correctly. If you are pretty sure, attaching your crafttweaker.log would be more helpful.

**Comment by jimmy06200** [comment]
I play on e2e 1.12.2 with latest crattweaker 2 and go through all the mod one by one and sad when I upload tconevo, it dismach old and new recepies but the new one are uncraftable. I will send you the craft log tonight when ill be at home

**Comment by jimmy06200** [comment]
[crafttweaker.log](https://github.com/phantamanta44/tinkers-evolution/files/4955019/crafttweaker.log)

**Comment by jimmy06200** [comment]
Hope you can find something i still love this mod and love to play with it

**Comment by phantamanta44** [comment]
which recipes in particular are broken, and how?

**Comment by jimmy06200** [comment]
All recipes in general it duplicate the old recepies and new one but only the old one can be craft...

**Comment by jimmy06200** [comment]
Find it finally one of e2e material made the craft tweaker recepies craft completly !!!!! thx
