### ISSUE TITLE
Fatal incompat with Pewter

### ISSUE THREAD

**Issue by ChromaPIE** [phantamanta44/tinkers-evolution#29]
The registry of osmium by TConEvo would prevent the same one from Pewter from successfully registering, thus crash the game when launching.

CR: https://paste.ubuntu.com/p/MwH9vmgX9g/

**Comment by phantamanta44** [comment]
does disabling the osmium material from one of the mods not work?

**Comment by Suy1qing** [comment]
I disabled osmium in pewter.cfg but still crashing the game when launch.
I check the crash log and it said osmiun already register in this mod.

**Comment by phantamanta44** [comment]
is your crash different from the one above? from the bits of pewter source code that i've seen, it seems like disabling the material should completely kill registration

**Comment by Suy1qing** [comment]
My crash is same as the one above. I do disable all the material in pewter.cfg, it still shows **Material "osmium": It was already registered by Tinkers' Evolution**

**Comment by phantamanta44** [comment]
i've just tested with this pewter config, and it loads without crashing:
```
"material blacklist:" {
    # Blacklist for Pewter Materials. Add the materials you don't want and they will not be loaded on startup [default: ]
    S:materialBlacklist <
        starmetal
        livingwood
        livingrock
        manasteel
        elementium
        terrasteel
        manastring
        osmium
        thaumium
        voidmetal
     >
}
```

**Comment by phantamanta44** [comment]
i am unsure of wheter this is user error related to incorrectly configuring pewter or an actual bug. please try this config and report the results when you have time

**Comment by Suy1qing** [comment]
I re-verify again, finally find the reason is another mod,**conarm**.
It is a armor mods based on Tinkers' Construct 2.
If you load this mod, even you disable all materials in pewter.cfg. It still crash within the reason above.

**Comment by phantamanta44** [comment]
i also have conarm installed. it may be armoury expansion...

**Comment by phantamanta44** [comment]
i've just tested with pewter, conarm, and armoury expansion all installed and there's no crash, so i'm really unsure of what could possibly be going wrong here. if you have a new crashlog implicating conarm, i would like to see it

**Comment by Suy1qing** [comment]
I put conarm and armoury epxpansion, it will crash.
I am chinese, so i edit some chinese in .jar files. This will not bother you to check crash log.
https://paste.ubuntu.com/p/G2Y73pTG5b/
please check log for details, it is the same as above.(I think)

**Comment by phantamanta44** [comment]
can i get a copy of your config directory?

**Comment by Suy1qing** [comment]
[config.zip](https://github.com/phantamanta44/tinkers-evolution/files/5046768/config.zip)
I put all config folder to you for details.

**Comment by phantamanta44** [comment]
i'm still unable to replicate the issue... is this modpack available on curseforge, by any chance?

**Comment by Suy1qing** [comment]
I use this config folder and launch successfully if not install conarm, is it any possible I add some chinese characters in .jar files name? I delete this and try again.

**Comment by Suy1qing** [comment]
Fine..
I delete chinese characters and successfully launch within conarm,pewter and TConEvo.
Please close this issue and thanks for your support.

**Comment by phantamanta44** [comment]
that's really weird, but i'm glad it's resolved
