### ISSUE TITLE
crash with ic2 classic?

### ISSUE THREAD

**Issue by Plaxaris92** [phantamanta44/tinkers-evolution#33]
Hi, i'm having troubles with this mod, every time i try to play the game crashes on startup, is there anything i can do? I don't really konw anything about java :c
Here is the crash log https://pastebin.com/PZv18Cty

**Comment by phantamanta44** [comment]
ic2 classic uses the same mod id as ic2 for some reason :I

I'll probably have to do some weird special-casing to get around that

**Comment by Plaxaris92** [comment]
The game works well and without any problems in the latest version c:
