### ISSUE TITLE
CraftTweaker: Cant get item list from 

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/tinkers-evolution#34]
TconEvo version: 1.0.31

For modpack making purposes i need to iterate through all items in a mod.
This function usually return all items in a mod, but with **tconevo** its return only few items:
```js
for item in itemUtils.getItemsByRegexRegistryName(".*tconevo:.*") {
  print(item.displayName);
}
```

return:
```
Pink Slimy Mud
Raw Meat Ingot
Internal Item
Coalescence Matrix
Wyvern Metal Ingot
Wyvern Metal Block
Arcane Focus
Sceptre
```

Feels like items is not loaded completely.
Am i do something wrong, or there is no way to get items with this function?

**Comment by phantamanta44** [comment]
it seems like this is correct behaviour: it produces a list of all the registered items in the mod. it's important to note that many of the "items" are just sub-items (i.e. differentiated by metadata) -- for example, all the other metal ingots are sub-items of the item listed as "wyvern metal ingot"

**Comment by Krutoy242** [comment]
Seems like you are right...
I was intended to remove all gear recipes, but i would use another way then.
Thank you for fast answer!
