### ISSUE TITLE
Support for Equivalent additions

### ISSUE THREAD

**Issue by Collecter128** [phantamanta44/tinkers-evolution#38]
I suggest adding support for ProjectE’s add on Equivalent Additions blue matter https://www.curseforge.com/minecraft/mc-mods/equivalent-additions

**Comment by phantamanta44** [comment]
I don't think it's particularly meaningful to add equipment for blue matter:

* Equivalent Additions itself doesn't even add blue matter equipment
* Red matter equipment is pretty much already as powerful as it gets without being as overpowered as infinity equipment
