### ISSUE TITLE
How to close the association of a mod

### ISSUE THREAD

**Issue by axin0452** [phantamanta44/tinkers-evolution#40]
How to turn off the association of a certain mod, I want to turn off the association of avaritia

**Comment by phantamanta44** [comment]
you'll just want to disable all the materials for that mod using the `disabledMaterials` config entry

**Comment by axin0452** [comment]
@phantamanta44 If I want to disable avartia's equipment, how should I fill it in the configuration file? I tried for a long time and failed
`    S:disabledMaterials <
        avaritia:resource:6
        avaritia
     >`

**Comment by phantamanta44** [comment]
you'll want the material ID, which is `infinity_metal` for infinity ingots

**Comment by axin0452** [comment]
@phantamanta44 Fill in infinity_ Metal does work, effectively blocking the association of avartia mod.

Another problem arises..  How to get it infinity_ metal. If I want to disassociate other mods. How do I get this ID

**Comment by phantamanta44** [comment]
they're given in [this source file](https://github.com/phantamanta44/tinkers-evolution/blob/1.12.2/src/main/java/xyz/phanta/tconevo/constant/NameConst.java). you can also find them by reading the nbt data for tool parts in-game
