### ISSUE TITLE
Sentient problem

### ISSUE THREAD

**Issue by jimmy06200** [phantamanta44/tinkers-evolution#41]
Hi i trey today a sentient weapon and it doesnt seem to drop soul. A little help please ?

**Comment by phantamanta44** [comment]
if you have a tartaric gem in your inventory, the will gets absorbed directly into the gem

**Comment by jimmy06200** [comment]
i do have one but it doesnt gain will, it just lost it each kills XD idk

**Comment by phantamanta44** [comment]
sentient tools do cost will to use, so it might be the case that the mobs you're killing drop less will than the sword consumes

**Comment by jimmy06200** [comment]
okay i can understand but sad the two proc at the same time
