### ISSUE TITLE
Just another uncraftable thing showing up in a recipe from Avaritia

### ISSUE THREAD

**Issue by ChromaPIE** [phantamanta44/tinkers-evolution#42]
Two raw meat ingots add theirselves to the recipe of cosmic meatballs from Avaritia, without the specific mod it would make those endgame things uncraftable.

Not a fatal problem, no hurry, but worths a fix.

**Comment by phantamanta44** [comment]
same as #8; this is a problem with codechickenlib and they should fix it on their end

**Comment by phantamanta44** [comment]
actually no, this is on my end. i'll work it out later
