### ISSUE TITLE
How to disable sceptre

### ISSUE THREAD

**Issue by axin0452** [phantamanta44/tinkers-evolution#49]
How to disable sceptre
`    # A list of tool modifiers that should be disabled.
    S:disabledModifiers <
        tconevo:tool_sceptre
        tool_sceptre
     >`

**Comment by phantamanta44** [comment]
as of now, you can't

**Comment by axin0452** [comment]
@phantamanta44 I'm sorry, I misunderstood.So how is this option used? Can you give me an example?

**Comment by phantamanta44** [comment]
this option is for disabling tool modifiers, not tools. you cannot disable the sceptre for the time being
