### ISSUE TITLE
Suggestion avaritia Enhancement Crystal

### ISSUE THREAD

**Issue by edotenseilove** [phantamanta44/tinkers-evolution#5]
Hallo

Apart from invincible Armor from Infinity ingots countered only by chaos damage.
I have a suggestion about making a support for avaritia Enhancement Crystal as a modifier  which would allow something called modifier  evolution which would do for example one od these:

1.  IT would allow Enchanting tools in enchantment table
2. Change of certain modifiers to evolved versions:
 evolved luck modifier with  higher max level (when crystal Is applied And luck is already applied Luck modifier will reset to zero but offer higher max level after(configurable) if luck modifier Is not applied IT would automaticky Evolve IT when luck is applied)
Evolved redstone modifier (more levels or higher increase in speed)
Evolved Sharp modifier (same as redstone but with Attack damage)
Evolved Diamond (higher stat increase)
Evolved Reinforced (one or two levels would make Tool unbreakable)
And so on

I believe that evolution of modifiers would be a great addition to the mod.

ONLY thing Is that you would have to  recreate all modifiers to work that way just like you did in Tinkers' Modifier Modifier addon with custom reinforced modifier And that would take some time.

**Comment by phantamanta44** [comment]
i don't know about this one. it would take an enormous amount of work just to support what is basically just a meme mod
