### ISSUE TITLE
[1.12.2] 'Energized' Armor Trait is bugged where it uses both Energy & Durability if you gain Armor from wearing regular armor or by other means

### ISSUE THREAD

**Issue by SonicX8000** [phantamanta44/tinkers-evolution#51]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 13
CodeChickenLib-1.12.2-3.2.3.358-universal
CoFHCore-1.12.2-4.6.6.1-universal
CoFHWorld-1.12.2-1.4.0.1-universal
conarm-1.12.2-1.2.5.9
jei_1.12.2-4.15.0.291
libnine-1.12.2-1.1.9
Mantle-1.12-1.3.3.55
RedstoneArsenal-1.12.2-2.6.4.1-universal
RedstoneFlux-1.12-2.1.1.1-universal
tconevo-1.12.2-1.0.33
TConstruct-1.12.2-2.13.0.183
ThermalExpansion-1.12.2-5.5.6.1-universal
ThermalFoundation-1.12.2-2.6.6.1-universal

=====

The Energized Armor Trait grants a ConArm Armor Piece an energy buffer that is used before durability, however if you wear something that gives you an increase in armor, such as a vanilla Leather Cap, Iron Helmet, Diamond Boots, etc. This will bug the trait where it'll use both the energy as well as the durability.

Here's a gif of it in action, using an Iron Helmet with a Fluxed Electrum Chestplate.
[GIF](https://cdn.discordapp.com/attachments/377171551155650560/761716499492503602/Energizedarmortraitbug.gif)

Toughness also causes this bug to occur, although I had to install these mods...

cyberware-1.12.2-0.2.11.26
ReWIRED-1.0.9b

...which has Nerco Limbtic Limbs that grants +1 Armor Toughness if you get some surgery done. Vanilla has Armor that gives Toughness via Diamond Armor but it's paired with giving Armor so needed to test it with it giving Toughness alone.

**Comment by phantamanta44** [comment]
looks like this is a problem with conarm in general, and it's not easy to fix without Yet Another Coremod Hack(tm). i'll look into it more in a future update, but it's on hold for the moment

**Comment by SonicX8000** [comment]
Issue still exists with "tconevo-1.12.2-1.0.35"
