### ISSUE TITLE
v1.0.36 crashes with ProjectE during startup

### ISSUE THREAD

**Issue by TCreopargh** [phantamanta44/tinkers-evolution#54]
Full crash report here:
https://paste.ubuntu.com/p/Dc9nKmvHjb/
Rolling back to earlier versions of tconevo or just uninstalling the mod fixes the issue, although the crash report only mentioned ProjectE
I've tried to change a few config options but had no luck

**Comment by phantamanta44** [comment]
this appears to be a conflict with better hurt timers rather than project: e

**Comment by TCreopargh** [comment]
> this appears to be a conflict with better hurt timers rather than project: e

Oh, thanks for pointing it out, I'll check that mod later
