### ISSUE TITLE
Tinkers' Evolution and Solar Flux Reborn Crash

### ISSUE THREAD

**Issue by ghost** [phantamanta44/tinkers-evolution#57]
crash-report is here
[crash-2020-10-24_14.24.57-client.txt](https://github.com/phantamanta44/tinkers-evolution/files/5432551/crash-2020-10-24_14.24.57-client.txt)
Can you help me see what happened?
Perhaps the reason is too many mods?
(sorry, my english too bad)

**Comment by phantamanta44** [comment]
is your solarflux version out of date?

**Comment by ghost** [comment]
ok...
i upgraded solar flux verison 
not crashing anymore
thanks!
