### ISSUE TITLE
Crash when entering minecraft

### ISSUE THREAD

**Issue by addtioe** [phantamanta44/tinkers-evolution#59]
[crash-2020-10-26_22.09.49-client.txt](https://github.com/phantamanta44/tinkers-evolution/files/5468436/crash-2020-10-26_22.09.49-client.txt)

**Comment by phantamanta44** [comment]
it looks like pewter loads after tconevo, so it tries to register its own thaumium without checking to ensure that no other mod has registered thaumium yet. perhaps there's a pewter config option to disable thaumium?
