### ISSUE TITLE
Incompatibility Valkyrien Skies

### ISSUE THREAD

**Issue by TheidenHD** [phantamanta44/tinkers-evolution#64]
Only Valkyrien Skies and Tinkers' Evolution(+Dependencies) are installed. Immediate crash.
https://pastebin.com/nHc99HYu

Mixin apply failed mixins.valkyrienskies.json:entity.MixinEntity -> net.minecraft.entity.Entity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PROTECTED @overwrite method func_174806_f in mixins.valkyrienskies.json:entity.MixinEntity cannot reduce visibiliy of PUBLIC target method

In https://github.com/phantamanta44/tinkers-evolution/blob/1.12.2/src/main/resources/tconevo_at.cfg you change  it from PROTECTED to PUBLIC and Valkyrien Skies tries to overwrite it.

**Comment by phantamanta44** [comment]
this is their issue, since overwriting a method is extremely invasive. i would suggest simply increasing the visibility of the overwriting method so no conflict with ATs is possible
