### ISSUE TITLE
[1.12.2]After changing the name of the MOD, starting Minecraft crashes

### ISSUE THREAD

**Issue by binglingyao** [phantamanta44/tinkers-evolution#65]
mod versions : 
- tconevo-1.12.2-1.0.38
- libnine-1.12.2-1.2.0

issues: 
- After changing  [tconevo] mod name, launch Minecraft crash. 
(After change >> [服务端][客户端][匠魂拓展-进化]tconevo-1.12.2-1.0.38.jar)
- Libnine has the same problem.
(After change >> [服务端][客户端][前置]libnine-1.12.2-1.2.0.jar)

logs:
[https://github.com/binglingyao/Minecraft-Logs/blob/main/crash-2020-12-05_06:44.21-client.txt](url)

**Comment by binglingyao** [comment]
I can be sure that resetting the MODS name and changing it back will solve this problem

**Comment by phantamanta44** [comment]
okay this is a little silly: forge loads mods in the order that it iterates through filenames; by renaming tconevo, you made it load before materialis. both materialis and tconevo register a tin material, but tconevo handles conflicts with existing materials gracefully but materialis does not. the solution, then, is simply to disable the tin material from one mod or the other
