### ISSUE TITLE
Can't launch minecraft after adding Tinkers Evolution

### ISSUE THREAD

**Issue by Tenshizera** [phantamanta44/tinkers-evolution#66]
[crash-2020-12-07_16.46.11-client.txt](https://github.com/phantamanta44/tinkers-evolution/files/5654630/crash-2020-12-07_16.46.11-client.txt)

**Comment by phantamanta44** [comment]
it looks like the "materialis" mod is adding a tin material that conflicts with tconevo's. you should use the config to disable tin in one of the two mods.

also, I recommend at least looking at the crash report before opening an issue, since you would have seen:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Materialis (materialis)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "tin": It was already registered by Tinkers' Evolution
```
