### ISSUE TITLE
Stoneblock 2 crash

### ISSUE THREAD

**Issue by yeetgrenadewastaken** [phantamanta44/tinkers-evolution#67]
So I added this mod to stoneblock two, and while for the most part it works, it seems that whenever I catch on fire the game crashes, telling me that Tinkers evolution is causing an issue

**Comment by phantamanta44** [comment]
do you have a crash log?

**Comment by yeetgrenadewastaken** [comment]
It would simply say not responding when I pressed get link, and when I
closed the game it would give me error code zero. It seems to be something
to do with status effects, as even with fire resistance on the game still
crashes, and when i go into witchwater(poisons, blinds, and withers you) i
get the same issue. when crashing it just says it identified tconevo as a
crash cause

**Comment by phantamanta44** [comment]
if you don't mind, I'd like to see a full game log then

**Comment by yeetgrenadewastaken** [comment]
do you want the entire latest.log file or the log document when the game
crashed?

**Comment by yeetgrenadewastaken** [comment]
wait... I just tried tconevo with the same mods just a different world and it worked fine. I did this to try to recreate the crash so I could try getting a crash report, but it has completely stopped crashing, and I can't find the log with the crash report because they are all just random giberish: 
![Untitled drawing (16)](https://user-images.githubusercontent.com/75183344/102676462-86d28780-4152-11eb-81dc-934ed2fc92f0.png)

**Comment by phantamanta44** [comment]
i guess if everything is okay for now, then i'll close this until it becomes an issue again

**Comment by yeetgrenadewastaken** [comment]
ok. sorry for wasting your time

**Comment by phantamanta44** [comment]
don't worry, it's not a problem

**Comment by yeetgrenadewastaken** [comment]
oh btw, do you know if there would be a way to integrate the draconic
evolution tconstruct gear with thedraconic evolution GUI?

**Comment by phantamanta44** [comment]
#3

**Comment by yeetgrenadewastaken** [comment]
k
