### ISSUE TITLE
Tinkers evolution and EnderIO crash

### ISSUE THREAD

**Issue by border999** [phantamanta44/tinkers-evolution#68]
https://gist.github.com/border999/d129aa5c3621877b17b30a02b9c346c5

**Comment by phantamanta44** [comment]
you appear to be using enderio version `5.3.1293-nightly`, when the latest released version of enderio is 5.2.x. I have no idea where you acquired this build, but it's too new for tconevo to support.

**Comment by border999** [comment]
https://ci.tterrag.com/job/EnderIO-Modules/
nightly builds of EnderIO

**Comment by border999** [comment]
nightly builds of EnderIO

**Comment by border999** [comment]
https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/changes
here is the log of the changes that each version has made, so you can find up to what version it would still work
I'm thinking it's this one that changed things. There's a note about making solars extendable. https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/1287/changes

**Comment by border999** [comment]
I'm thinking it's this one that changed things. https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/1287/changes

**Comment by border999** [comment]
now that I've shown you this. I'm hoping you'll take a look at the new things and start maybe preparing code to accept future release features and changes. Prevent bugs before they are ever reported. At least for changes that can be accounted for without doing more than you're comfortable with.

**Comment by border999** [comment]
hello?

**Comment by phantamanta44** [comment]
sorry, but i have no intention of "fixing" this crash as it stands. as the breaking api changes on enderio's side only exist in nightly builds, to update tconevo to accomodate the changes would be to drop support for all existing current enderio releases, which is unacceptable

**Comment by border999** [comment]
very well. Just please note the changelogs for the nightly builds so you can see what problems may arise in the later public releases.

**Comment by border999** [comment]
Would it be possible to request a feature that simply let's me turn off the integration with ender IO? Or disable the solar addon so that it doesn't trigger the crash?
