### ISSUE TITLE
Is it still caused by tconevo-1.12.2-1.0.17?

### ISSUE THREAD

**Issue by ChromaPIE** [phantamanta44/tinkers-evolution#7]
CR is here: 
[crash-2020-06-23_17.54.29-client.txt](https://github.com/phantamanta44/tinkers-evolution/files/4818626/crash-2020-06-23_17.54.29-client.txt)

**Comment by phantamanta44** [comment]
can i get a full log instead of just the crash report?

**Comment by ChromaPIE** [comment]
Sure.

[latest.log](https://github.com/phantamanta44/tinkers-evolution/files/4820575/latest.log)

**Comment by phantamanta44** [comment]
i'm not really certain whether this is tconevo's fault or not, but i found one possible bug that might cause it. i'm having a little trouble replicating it on my end, so please try [the latest build on curseforge](https://www.curseforge.com/minecraft/mc-mods/tinkers-evolution/files/2987023) and report back. thanks

**Comment by ChromaPIE** [comment]
Solved! Thank you.
