### ISSUE TITLE
primordial nulifies AOE

### ISSUE THREAD

**Issue by yeetgrenadewastaken** [phantamanta44/tinkers-evolution#70]
the primordial attribute prevents weapons with area of effect damage(such as broadswords and draconic evolution weapons upgraded with attack AOE) from doing area of effect damage. additionally, chaotic damage does not count towards xp for tinker's tool leveling meaning it is impossible to level up a fully primordial weapon

**Comment by phantamanta44** [comment]
i can see the issue with tool leveling, but i can't reproduce the issue with weapon aoe. i've tested with various broadswords and scythes with 100% chaos damage conversion and they still correctly deal damage in an area
