### ISSUE TITLE
[1.12.2] Natura Wood outputs as Vanilla Wood for making parts.

### ISSUE THREAD

**Issue by SonicX8000** [phantamanta44/tinkers-evolution#78]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 7
conarm-1.12.2-1.2.5.10
jei_1.12.2-4.15.0.291
libnine-1.12.2-1.2.0
Mantle-1.12-1.3.3.55
natura-1.12.2-4.3.2.69
tconevo-1.12.2-1.0.38
TConstruct-1.12.2-2.13.0.183

-----
![TENaturaWoodBug](https://user-images.githubusercontent.com/36653806/106832197-d6afd400-6656-11eb-9d43-f38473e73201.PNG)
Logs/Planks from Natura (Ghost, Fuse, Dark & Blood) will output as vanilla wood materials when put in the part builder.

If PlusTiC is installed the planks will output with the correct materials but the logs still output as vanilla wood materials.

**Comment by phantamanta44** [comment]
i suspect this has something to do with the order that mods are loaded in, which determines which mod registers the wood material first :I

the fix should probably be as simple as forcing tconevo's wood materials to register before vanilla tcon's, but it seems to be a little tricky to figure out how to do that
