### ISSUE TITLE
崩溃了，不知道为什么

### ISSUE THREAD

**Issue by Cayln-s** [phantamanta44/tinkers-evolution#79]
[错误报告 - 1.12.2-生存.zip](https://github.com/phantamanta44/tinkers-evolution/files/5964956/-.1.12.2-.zip)

**Comment by phantamanta44** [comment]
There's a material conflict with Materialis. Tinkers' Evolution adds tin, then Materialis also tries to add tin and crashes. You'll want to disable the tin material from one of the mods.

**Comment by Cayln-s** [comment]
> There's a material conflict with Materialis. Tinkers' Evolution adds tin, then Materialis also tries to add tin and crashes. You'll want to disable the tin material from one of the mods.

Can i ask how to disable the tin from one of the mods?If you can teach me, I will be very grateful .I am just a newbie on it.

**Comment by phantamanta44** [comment]
in either  `materialis.cfg` or `tconevo.cfg` in your `config` folder, there's a blacklist that lets you specify certain materials to disable
