### ISSUE TITLE
Any charged item can trigger the Final Guard effect when KeepInventory is true

### ISSUE THREAD

**Issue by TCreopargh** [phantamanta44/tinkers-evolution#80]
Version: tconevo-1.12.2-1.0.38
Looks like any charged armor will trigger the Final Guard effect every time the wearer dies (without losing any energy) and make the wearer become literally invincible. Looks like fluxed, energized and evolved trait all have this effect, although the Final Guard trait is disabled in config and no other modifiers are applied. 

Modpack: https://www.curseforge.com/minecraft/modpacks/greedycraft
Log: https://paste.ubuntu.com/p/s4k6jdkKdy/

**Comment by TCreopargh** [comment]
UPDATE: Looks like this only happens when gamerule 'KeepInventory' is true

**Comment by phantamanta44** [comment]
well, that's a little embarrassing: i forgot to check if the user's armour has final guard before applying the effect...
