### ISSUE TITLE
[Request] Enable Modules without the mods.

### ISSUE THREAD

**Issue by Filostorm** [phantamanta44/tinkers-evolution#86]
Hello! First I want to say I just found this mod and it looks awesome!

Second, my pack has Tech Reborn in it, which adds UU Matter, and I thought it would be cool to use the UU Metal. However, there is only the block shown, and I'm not sure how/what mod I need to enable it. 

So I'd like to request the ability to enable mod locked materials, or just adding UU Metal if Tech Reborn is installed.

Thank you!

**Comment by phantamanta44** [comment]
normally, uu-metal requires IC2. i've added a force-load material list to the config that lets you bypass the usual material loading requirements. you'll have to add recipes yourself using crafttweaker or something, though, since the built-in recipes are designed only for IC2

**Comment by Filostorm** [comment]
Awesome, thank you!
