### ISSUE TITLE
Crash when initializing, I don't know the issue

### ISSUE THREAD

**Issue by crazydud24** [phantamanta44/tinkers-evolution#87]
I am currently playing with a huge list of mods and today I added a handful of addons to tinkers construct. I don't know what is causing the crash. I have limited knowledge of coding and can only partially understand the crash report but I don't see a reason for it to have died. Minecraft loaded all the way to the final initialization step then died at the last second.
[crash-2021-04-16_19.17.44-client.txt](https://github.com/phantamanta44/tinkers-evolution/files/6328276/crash-2021-04-16_19.17.44-client.txt)

**Comment by phantamanta44** [comment]
i think your solar flux version might be out of date. try updating to the latest one and see if that fixes it
