### ISSUE TITLE
Incompatibility with ThaumicAugmentation

### ISSUE THREAD

**Issue by festro** [phantamanta44/tinkers-evolution#90]
When trying to load the mod with ThaumicAugmentation I get a CTD around the 3rd stage of loading the game. I am directed to ThaumicAugmentation as being the culprit with this crash report https://paste.dimdev.org/zerafafiye.mccrash, however when disabling Tinkers' Evolution the game loads fine. I've brought this up with the other mod author too.

**Comment by phantamanta44** [comment]
yeah i messed up a coremod; see #89. i've actually just now published the release that fixes it, so you can go get it on curseforge now
