### ISSUE TITLE
Support for Tinker's Slash Blade

### ISSUE THREAD

**Issue by arrester-002** [phantamanta44/tinkers-evolution#91]
With Tinkers' Evolution chaotic, I can create Tinker's SlashBlade, but when I try to upgrade it crashes because it is not supported. Please consider the support of Tinker's Slash Blade.

**Comment by arrester-002** [comment]
Postscript: Even if I used the command, it didn't work.

**Comment by phantamanta44** [comment]
do you have a crash log for this?

**Comment by arrester-002** [comment]
[crash-2021-04-20_21.09.42-client.txt](https://github.com/phantamanta44/tinkers-evolution/files/6488774/crash-2021-04-20_21.09.42-client.txt)

**Comment by arrester-002** [comment]
If it is a command, it will not crash.
I get an error.

**Comment by arrester-002** [comment]
I think this is a failure because SlashBlade itself is a special tool. I haven't done it yet, but it's possible that Astral Sorcery's Attunement isn't supported either.
