### ISSUE TITLE
Material stats from this mod can't be tweaked with stat tweaking mods like TweakersConstruct

### ISSUE THREAD

**Issue by TCreopargh** [phantamanta44/tinkers-evolution#95]
This happens since 1.0.39. Downgrading to 1.0.38 fixes the issue.
Stats of materials from this mod since 1.0.39 can't be tweaked with TweakersConstuct, they just remain their original stat. No error log related to this can be found.
However traits can still be tweaked.

**Comment by phantamanta44** [comment]
does it still not work on the latest version?

**Comment by TCreopargh** [comment]
I was using the latest version when I posted this issue and the mod hasn't been updated since then.

**Comment by Krutoy242** [comment]
Experience same issue on version 1.0.42.
Also, tweaks cant be applied with [Tool Progression](https://www.curseforge.com/minecraft/mc-mods/tool-progression) mod (mining levels).

Things get worst: I cant downgrade to 1.0.38, because old versions not supporting new EnderIO builds.
I need mining level tweaks, because have custom material progression, and TConEvo materials may spoil it:
![](https://i.imgur.com/XC50Ydj.png)

**Comment by Krutoy242** [comment]
Issue persist on new version (1.0.43).

Im using [Tweakers Construct](https://www.curseforge.com/minecraft/mc-mods/tweakers-construct) to change mining levels.
This example of several lines of tweaks:
```py
        aquamarine:131:5.25:3:0:d:d:d:d:d:d
        osmium:d:d:d:5:d:d:d:d:d:d
        ma.supremium:d:d:22.55:10:d:d:d:d:d:d
```
4th number between `:` means mining levels.
Aquamarine set to `0` `Flint`, but actually has `1` `Copper`.
Osmium set to `5` `Osmium`, but actually has `2` `Certus`.

Materials from other mods tweaked fine. Supremium from *Mystical Agradditions* set to `10` `Enderium` shows valid result.

<img src="https://i.imgur.com/hPueVbd.png" width=400>  
<img src="https://i.imgur.com/ozNwejV.png" width=400>
<img src="https://i.imgur.com/3oKfCwP.png" width=400>  

I also tried to change mining level of Osmium from *Tool Progression* mod, by adding this line to its config:
```py
    S:osmium=5
```
This worked fine before 1.0.39 (not sure), but now has no effect.


Files:
[tconevo.cfg](https://github.com/phantamanta44/tinkers-evolution/files/6703980/tconevo.zip)
[debug.log](https://github.com/phantamanta44/tinkers-evolution/files/6703967/debug-working.zip)

**Comment by phantamanta44** [comment]
`>:I`

**Comment by phantamanta44** [comment]
should be fixed now... i think

**Comment by Krutoy242** [comment]
Thank you! Now it tweaks fine.
