### ISSUE TITLE
crashes when used in ftb academy

### ISSUE THREAD

**Issue by BreazyLantern** [phantamanta44/tinkers-evolution#96]
I added it to ftb academy and it causes crashes for the modpack.
[crash-2021-05-13_17.50.02-server.txt](https://github.com/phantamanta44/tinkers-evolution/files/6475281/crash-2021-05-13_17.50.02-server.txt)

**Comment by phantamanta44** [comment]
ftb academy's draconic evolution version is too old. update it, and the crash should be gone

**Comment by BreazyLantern** [comment]
that works thank you
