### ISSUE TITLE
Crash when using new version of Ender IO together with this mod

### ISSUE THREAD

**Issue by Skogen787** [phantamanta44/tinkers-evolution#97]
Mod Version: 1.0.41

Title pretty much explains it, dont know what else to say

Crash Report:
https://pastebin.com/aXQiExfw

**Comment by magcicada** [comment]
https://github.com/phantamanta44/tinkers-evolution/issues/68

**Comment by magcicada** [comment]
This issue was raised a long time ago, but it was not resolved in time.
