### ISSUE TITLE
A crash report

### ISSUE THREAD

**Issue by mxancl** [phantamanta44/tinkers-evolution#98]
I encounter a problem while I use this mod.
This is the crash report
https://paste.dimdev.org/odofababem.mccrash

**Comment by phantamanta44** [comment]
your enderio version is very out-of-date

**Comment by mxancl** [comment]
Thank you.

**Comment by Krutoy242** [comment]
I experience same crash.
I cant update EnderIO, because [some other mods didnt updated yet and crashing game](https://github.com/Shadows-of-Fire/EnderTweaker/issues/21), so i forced to use old version.

**Comment by phantamanta44** [comment]
you'll just have to use an older version of tconevo for now
