### ISSUE TITLE
Primal Metal Ingot recipe require non-damaged Pearl

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/tinkers-evolution#99]
![](https://git.io/Jt8wf "Primal Metal Ingot") Require non-damaged ![](https://git.io/J3xSe "Primordial Pearl") in recipe.  
This is probably unintentional, because all other recipes that used Pearl accept it on **any damage**.

<img src="https://i.imgur.com/wwgsWau.png" width=400>

Video proof:
https://i.imgur.com/c2Vqe0W.mp4

**Comment by phantamanta44** [comment]
yeah, definitely not intentional
